### ISSUE TITLE
Change `className` to `class` when expanding div class names

### ISSUE THREAD

**Issue by Braayy** [olrtg/emmet-language-server#29]
Hi! I'm using SolidJS on my project, but the default behavior of emmet is to expand `.text-center` to `<div className="text-center"></div>`. The problem is that SolidJS does not use `className`, only `class`.

I've search how to change this behavior, and found this: [How to change emmet expanding "className" to "class" in VSCode for JSX/TSX?](https://stackoverflow.com/questions/57538644/how-to-change-emmet-expanding-classname-to-class-in-vscode-for-jsx-tsx).

So i tried putting this configuration on Helix:
```toml
[language-server.emmet-ls]
command = "emmet-language-server"
config = { includeLanguages = { typescriptreact = "html" } }
args = ["--stdio"]
```

But nothing changed, even if a use:
```toml
[language-server.emmet-ls]
command = "emmet-language-server"
config = { emmet = { includeLanguages = { typescriptreact = "html" } } }
args = ["--stdio"]
```

The config field is sent to `initializationOptions` of `onInitialize`.

Idk if the problem is with this lsp, emmet-helper or emmet itself.
