### ISSUE TITLE
Unable to use self-closing tags in vue files in Helix Editor

### ISSUE THREAD

**Issue by overbyte** [olrtg/emmet-language-server#41]
currently if i the do following in a JSX file in helix, I get a self closing tag, as expected: 

![jsx](https://github.com/olrtg/emmet-language-server/assets/402785/22a6ebc2-80a1-40ad-9017-1d6b7c5e9727)
 
however if i do the same thing in a .vue file i get the following result

![vue](https://github.com/olrtg/emmet-language-server/assets/402785/ee58181c-d73b-446d-8e97-53e630493dbf)

My Helix languages.toml includes the following 

```toml
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "vue"
language-servers = [ "vue-language-server", "emmet-lsp"]
formatter = { command = 'prettier', args = ["--parser", "vue"] }
auto-format = true
```

Can you tell me if I need to do anything to the Helix config to get the LSP to respond in the right way please?
